df <- fread("household_power_consumption.txt",na.strings = "?")
df <- subset(df,Date == "1/2/2007" | Date =="2/2/2007")
png(filename = "plot1.png",width=480,height=480)
hist(df$Global_active_power,xlab="Global Active Power (kilowatts)",ylab="Frequency",main="Global Active Power",col="red")
dev.off()
rm(df)